Update update-video-ids.yml

diff --git a/.github/workflows/update-video-ids.yml b/.github/workflows/update-video-ids.yml
--- a/.github/workflows/update-video-ids.yml
+++ b/.github/workflows/update-video-ids.yml
@@ -21,13 +21,23 @@ jobs:
           cat response.json | jq '[.data[] | .uri | split("/") | last] | {videoIds: .}' > data/videoIds.json
           echo "Fetched and parsed video IDs"
 
+      - name: Debugging: Check Git Config
+        run: |
+          git config --list
+          ls -la
+
       - name: Commit and push changes
         env:
           GH_PAT: ${{ secrets.GH_PAT }}
         run: |
+          set -e # Exit if any command fails
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+          echo "Setting remote URL"
           git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/rclaycock/vimeo-video-ids-cache.git
+          echo "Adding files to git"
           git add data/videoIds.json
+          echo "Committing changes"
           git commit -m "Update video IDs"
+          echo "Pushing changes"
           git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/rclaycock/vimeo-video-ids-cache.git HEAD:main
