Update update-video-ids.yml

diff --git a/.github/workflows/update-video-ids.yml b/.github/workflows/update-video-ids.yml
--- a/.github/workflows/update-video-ids.yml
+++ b/.github/workflows/update-video-ids.yml
@@ -14,13 +14,20 @@ jobs:
 
       - name: Fetch video IDs from Vimeo
         run: |
-          curl -H "Authorization: Bearer 8ad8207b523b00790698b612a88c5c2f" "https://api.vimeo.com/me/albums/11193887/videos" > response.json
+          set -e # Exit if any command fails
+          echo "Fetching video IDs from Vimeo"
+          curl -H "Authorization: Bearer 8ad8207b523b00790698b612a88c5c2f" "https://api.vimeo.com/me/albums/11193887/videos" -o response.json
+          cat response.json
           cat response.json | jq '[.data[] | .uri | split("/") | last] | {videoIds: .}' > data/videoIds.json
+          echo "Fetched and parsed video IDs"
 
       - name: Commit and push changes
+        env:
+          GH_PAT: ${{ secrets.GH_PAT }}
         run: |
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/rclaycock/vimeo-video-ids-cache.git
           git add data/videoIds.json
           git commit -m "Update video IDs"
           git push
